spring:
  datasource:
    url: "jdbc:h2:file:./target/database/h2"
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15

  batch:
    job:
      enabled: false

hapi:
  fhir:
    ### This is the FHIR version. Choose between, dstu2, dstu3, r4 or r5
    fhir_version: R4
    defer_indexing_for_codesystems_of_size: 101
    implementationguides:
      medcom_09:
        url: http://build.fhir.org/ig/hl7dk/dk-medcom/package.tgz
        name: dk.fhir.ig.medcom-core
        version: 1.0.2
      dk-core:
        url: http://build.fhir.org/ig/hl7dk/dk-core/package.tgz
        name: dk.fhir.ig.dk-core
        version: 0.9

    enable_repository_validating_interceptor: true

    tester:
      medcom:
        name: MedCom Tester
        server_address: https://fhir.medcom.dk/fhir
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
